name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install CMake and GoogleTest
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev

    - name: Install CMake
      uses: lukka/get-cmake@latest 
      with:
        cmakeVersion: 4.1.x

    - name: Configure CMake
      run: cd scripts; ./build.sh
      
    - name: Test
      run: cd scripts; ./test.sh
